apiVersion: v1
kind: ConfigMap
metadata:
  name: proxyd-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  config.toml: |
    # List of WS methods to whitelist.
    ws_method_whitelist = [
      "eth_subscribe",
      "eth_call",
      "eth_chainId",
      "eth_sendRawTransaction"
    ]

    # Enable WS on this backend group. There can only be one WS-enabled backend group.
    ws_backend_group = "sequencer"

    [server]
    rpc_host = "0.0.0.0"
    rpc_port = {{ .Values.proxyd.service.port | default 8080 }}
    ws_host = "0.0.0.0"
    ws_port = 8085  # WebSocket port, configurable if needed
    max_body_size_bytes = 10485760
    max_concurrent_rpcs = 1000
    log_level = "info"

    [redis]
    url = "{{ .Values.proxyd.endpoints.redis_url | default "redis://localhost:6379" }}"

    [metrics]
    enabled = true
    host = "0.0.0.0"
    port = 9761

    [backend]
    response_timeout_seconds = 5
    max_response_size_bytes = 5242880
    max_retries = 3
    out_of_service_seconds = 600
    max_latency_threshold = "30s"
    max_degraded_latency_threshold = "10s"
    max_error_rate_threshold = 0.3

    # Defining the backends
    [backends]
    [backends.sequencer]
    rpc_url = "{{ .Values.proxyd.endpoints.sequencer_rpc_url | default "http://localhost:8545" }}"
    ws_url = "{{ .Values.proxyd.endpoints.sequencer_ws_url | default "" }}"
    max_rps = 10
    max_ws_conns = 5

    [backends.replica]
    rpc_url = "{{ .Values.proxyd.endpoints.replica_rpc_url | default "http://localhost:8546" }}"
    ws_url = "{{ .Values.proxyd.endpoints.replica_ws_url | default "" }}"
    max_rps = 10
    max_ws_conns = 5

    # Defining backend groups
    [backend_groups]
    [backend_groups.sequencer]
    backends = ["sequencer"]

    [backend_groups.replica]
    backends = ["replica"]

    # Method mappings to specific backend groups
    [rpc_method_mappings]
    eth_sendRawTransaction = "sequencer"
    eth_subscribe = "replica"
    eth_call = "replica"
    eth_chainId = "replica"

    # Authentication
    [authentication]
    secret = "{{ .Values.proxyd.endpoints.auth_secret | default "abc" }}"
