apiVersion: v1
kind: ConfigMap
metadata:
  name: proxyd-config
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "proxyd-release"
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    # List of WS methods to whitelist.
    ws_method_whitelist = [
      "eth_subscribe",
      "eth_call",
      "eth_chainId"
    ]
    # Enable WS on this backend group. There can only be one WS-enabled backend group.
    ws_backend_group = "main"

    [server]
    rpc_host = "0.0.0.0"
    rpc_port = 8080
    ws_host = "0.0.0.0"
    ws_port = 8085
    max_body_size_bytes = 10485760
    max_concurrent_rpcs = 1000
    log_level = "info"

    [redis]
    url = "redis://proxyd-release-redis-master:6379"

    [metrics]
    enabled = true
    host = "0.0.0.0"
    port = 9761

    [backend]
    response_timeout_seconds = 5
    max_response_size_bytes = 5242880
    max_retries = 3
    out_of_service_seconds = 600
    max_latency_threshold = "30s"
    max_degraded_latency_threshold = "10s"
    max_error_rate_threshold = 0.3

    [backends.sepolia]
    rpc_url = "https://ethereum-sepolia-rpc.publicnode.com"
    ws_url = ""
    username = ""
    password = ""
    max_rps = 3
    max_ws_conns = 1
    consensus_receipts_target = "eth_getBlockReceipts"

    [backends.l2_rollup]
    rpc_url = "http://op-node:8545"
    username = ""
    password = ""
    max_rps = 10
    max_ws_conns = 5
    consensus_receipts_target = "eth_getBlockReceipts"

    [backend_groups.main]
    backends = ["sepolia", "l2_rollup"]
    consensus_aware = true

    [authentication]
    secret = "$AUTH_SECRET"

    [rpc_method_mappings]
    eth_call = "main"
    eth_chainId = "main"
    eth_blockNumber = "main"
