apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyd
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "proxyd-release"
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.proxyd.replicas }}
  selector:
    matchLabels:
      app: proxyd
  template:
    metadata:
      labels:
        app: proxyd
    spec:
      containers:
      - name: proxyd
        image: "{{ .Values.proxyd.image.repository }}:{{ .Values.proxyd.image.tag }}"
        command: ["/bin/proxyd"] 
        args: ["/etc/proxyd/config.toml"]
        ports:
        - containerPort: {{ .Values.proxyd.service.port }}
        volumeMounts:
        - name: proxyd-config-volume
          mountPath: /etc/proxyd
      volumes:
      - name: proxyd-config-volume
        configMap:
          name: proxyd-config
