apiVersion: v1
kind: Service
metadata:
  name: proxyd
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "proxyd-release"
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.proxyd.service.port }}
      targetPort: {{ .Values.proxyd.service.port }}
      nodePort: 30001
  selector:
    app: proxyd
