---
# Source: op-proposer/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: op-stack
  name: op-proposer
  labels:
    helm.sh/chart: op-proposer-0.1.2
    app.kubernetes.io/name: op-proposer
    app.kubernetes.io/instance: op-proposer
    app.kubernetes.io/version: "v0.10.13"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "op-stack-release"
    meta.helm.sh/release-namespace: "op-stack"
spec:
  serviceName: op-proposer
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: op-proposer
      app.kubernetes.io/instance: op-proposer
  template:
    metadata:
      namespace: op-stack
      labels:
        app.kubernetes.io/name: op-proposer
        app.kubernetes.io/instance: op-proposer
    spec:
      containers:
        - name: op-proposer
          image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v1.9.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: rpc-port
              containerPort: 8560
          command:
            - op-proposer
          args:
          - --poll-interval=12s
          - --rpc.port=8560
          - --rollup-rpc={{ .Values.endpoints.rollup_rpc_url }}
          - --l2oo-address=0xDd5842B43ea2Cb3EEb01FcceC26E3ce3663D3a53
          - --l1-eth-rpc={{ .Values.endpoints.l1_rpc }}
          - --private-key=$(OP_PROPOSER_PRIVATE_KEY)
          env:
            - name: OP_PROPOSER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: op-proposer-secret
                  key: proposerKey
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: rpc-port
          readinessProbe:
            # TODO: replace it to real http request.
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: rpc-port
          resources:
            {}