---
# Source: op-geth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: op-stack
  name: op-geth
  labels:
    helm.sh/chart: op-geth-0.1.2
    app.kubernetes.io/name: op-geth
    app.kubernetes.io/instance: op-geth
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "v1.10.26"
  annotations:
    meta.helm.sh/release-name: "op-stack-release"
    meta.helm.sh/release-namespace: "op-stack"
spec:
  type: LoadBalancer
  ports:
    # HTTP RPC
    - name: rpc-http-port
      port: 8545
      targetPort: 8545
    # WS RPC
    - name: rpc-ws-port
      port: 8546
      targetPort: 8546
    # AuthRPC
    - name: authrpc-port
      port: 8551
      targetPort: 8551
    # Metrics
    - name: metrics-port
      port: 7300
      targetPort: 7300
    # pprof
    - name: pprof-port
      port: 6060
      targetPort: 6060
  selector:
    app.kubernetes.io/name: op-geth
    app.kubernetes.io/instance: op-geth
    release: op-geth
