---
apiVersion: v1
kind: Service
metadata:
  namespace: op-stack
  name: op-geth-sequencer
  labels:
    app.kubernetes.io/name: op-geth-sequencer
    app.kubernetes.io/instance: op-geth-sequencer
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "op-stack-release"
    meta.helm.sh/release-namespace: "op-stack"
spec:
  type: NodePort
  ports:
    - name: rpc-http  
      port: 8545
      targetPort: 8545
    - name: rpc-ws 
      port: 8546
      targetPort: 8546
    - name: authrpc 
      port: 8551
      targetPort: 8551
    - name: metrics
      port: 7300
      targetPort: 7300
    - name: pprof
      port: 6060
      targetPort: 6060
  selector:
    app.kubernetes.io/name: op-geth-sequencer
    app.kubernetes.io/instance: op-geth-sequencer
