---
# Source: op-node/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: op-stack
  name: op-node
  labels:
    helm.sh/chart: op-node-0.1.2
    app.kubernetes.io/name: op-node
    app.kubernetes.io/instance: op-node
    app.kubernetes.io/version: "v0.10.13"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "op-stack-release"
    meta.helm.sh/release-namespace: "op-stack"
spec:
  serviceName: op-node
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: op-node
      app.kubernetes.io/instance: op-node
  template:
    metadata:
      namespace: op-stack
      labels:
        app.kubernetes.io/name: op-node
        app.kubernetes.io/instance: op-node
        
    spec:
      containers:
        - name: op-node
          image: "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.9.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: rpc-port
              containerPort: 8547
            - name: metrics-port
              containerPort: 7300
            - name: pprof-port
              containerPort: 6060
          command:
            - op-node
          args:
            # required values
            - --l1={{ .Values.endpoints.l1_rpc }}
            - --l1.rpckind=basic
            - --l2={{ .Values.endpoints.sequencer_rpc_url }}
            - --rpc.addr=0.0.0.0
            - --rpc.port=8547
            - --rpc.enable-admin=true
            - --sequencer.l1-confs=3
            - --verifier.l1-confs=3
            # rollup config
            - --rollup.config=/configmaps/rollup.json

            # jwt
            - --l2.jwt-secret=/secrets/jwt-secret.txt
            # sequencer
            - --sequencer.enabled=true
            - --p2p.sequencer.key=
            - --p2p.disable
            # metrics
            - --metrics.enabled=true
            - --metrics.addr=0.0.0.0
            - --metrics.port=7300

            # pprof
            - --pprof.enabled=true
          volumeMounts:
            # mounts all files in the Secrets.
            - mountPath: /secrets
              name: op-node-secret
            - mountPath: /configmaps
              name: op-node-configmaps
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: rpc-port
          readinessProbe:
            # TODO: replace it to real http request.
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: rpc-port
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
      volumes:
        - name: op-node-secret
          secret:
            secretName: op-node-secret
        - name: op-node-configmaps
          configMap:
            name: op-node-configmaps