---
apiVersion: v1
kind: Service
metadata:
  namespace: op-stack
  name: op-batcher
  labels:
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: op-batcher-0.1.2
    app.kubernetes.io/name: op-batcher
    app.kubernetes.io/instance: op-batcher
    app.kubernetes.io/version: "v0.10.13"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "op-stack-release"
    meta.helm.sh/release-namespace: "op-stack"
spec:
  type: ClusterIP
  ports:
    - name: rpc-port
      port: 8548
      targetPort: 8548

  selector:
    app.kubernetes.io/name: op-batcher
    app.kubernetes.io/instance: op-batcher
